<?php 
/**
 * 
 * @var CB\Helloworld\ViewModel\Computers @computer
 */
$computersVm = $block->getData('computer');
$computer = $computersVm->getComputersDetail();
?>
<div class="computer-detail-page">
	<div class="add-new-section">
		<a href="<?=$block->getUrl('helloworld/computer/list');?>"><?=__("All Computers")?></a>
	</div>
	<p><?=__('Computer Detail Page')?></p>
	<p>Company Name : <?= $escaper->escapeHtml($computer->getCompany());?></p>
	<p>Hard Disk : <?=$escaper->escapeHtml($computer->getHardDisk());?></p>
</div>