<div class="helloworld-computer-list">
	<div class="add-new-section">
		<a href="<?=$block->getUrl('helloworld/computer/add');?>">Create New Entry</a>
	</div>
	<div class="list-data">
		<ul id="list">
			<li><a href="<?=$block->getUrl('helloworld/computer/computerdetail',['id'=>1])?>">Dell</a></li>
			<li><a href="<?=$block->getUrl('helloworld/computer/computerdetail',['id'=>2])?>">HP</a></li>
			<li><a href="<?=$block->getUrl('helloworld/computer/computerdetail',['id'=>3])?>">Sony</a></li>
			<li><a href="<?=$block->getUrl('helloworld/computer/computerdetail',['id'=>4])?>">Samesung</a></li>
		</ul>	
		<div class="count">
			<?=__("Total Computer Count is %1", 4);?>
		</div>		
	</div>


	
</div>